#!/bin/bash
#HELLO=Hello
#	 function hello {
#		 local HELLO=World
 #                echo $HELLO
#	}
 #        echo $HELLO
  #       hello
   #      echo $HELLO



# if [ "foo" = "foo1" ];
#	 then
 #              echo expression evaluated as true
  #       else 
#	   echo falce	 
 #        fi


# for i in $(ls -ltr);
#	 do
 #           echo item: $i
  #      done


#  for i in `seq 1 10`;
 #       do
  #              echo $i
   #     done

#   COUNTER=0
 #        while [  $COUNTER -lt 10 ]; do
  #           echo The counter is $COUNTER
   #          let COUNTER=COUNTER+1
    #     done


 # COUNTER=20
  #       until [  $COUNTER -lt 10 ]; do
   #          echo COUNTER $COUNTER
    #         let COUNTER-=1
     #done

#     function quit {
 #            exit
  #         }
   #        function hello {
    #           echo Hello!
     #      }
      #     hello
       #    quit
        #   echo foo


# function quit {
 #                  exit
  #              }  
   #             function e {
#			    echo $2 
 #               }  
  #              e Hello
   #             e World
    #            quit
     #           echo foo 


#OPTIONS="Hello Quit"
      #     select opt in $OPTIONS; do
     #          if [ "$opt" = "Quit" ]; then
    #            echo done
   #             exit
  #             elif [ "$opt" = "Hello" ]; then
 #               echo Hello World
 #              else
       #         clear
        #        echo bad option
         #      fi
          # done


#if [ -z "$1" ]; then 
 #             echo usage: $0 directory
  #            exit
   #       fi
    #      SRCD=$1
     #     TGTD="/var/backups/"
      #    OF=home-$(date +%Y%m%d).tgz
       #   tar -cZf $TGTD$OF $SRCD

 #      cd /dada &> /dev/null
  #      echo rv: $?
   #     cd $(pwd) &> /dev/null
    #    echo rv: $?


 #   DBS=`mysql -uroot  -e"show databases"`
  #      for b in $DBS ;
   #     do
    #            mysql -uroot -e"show tables from $b"
     #   done

S1='string'
        S2='String'
        if [ $S1=$S2 ];
        then
                echo "S1('$S1') is not equal to S2('$S2')"
        fi
        if [ $S1=$S1 ];
        then
                echo "S1('$S1') is equal to S1('$S1')"
        fi
























































